wip
toshinori-m/stay_connect pull request #124
Opened 2024-02-20 09:45 UTC by toshinori-m

2024-02-21 04:35 UTC, hirosi1900day approved these changes

2024-02-21 10:15 UTC, toshinori-m commented
例外処理のerror: e.record.errors.messagesの箇所ですが、複数errorが発生したことを考慮しerrorsとしました。
同時にcreateアクションの箇所も修正しました。

よろしくお願いします。

2024-02-21 23:52 UTC, hirosi1900day approved these changes
素晴らしい！

2024-02-22 02:02 UTC, toshinori-m commented
このPRで改めてチーム新規作成と更新画面のテストを行なってみました。
すると、新規作成時の種目と年齢の登録が出来ていませんでした。
（これは、最初からなのか途中からなのかは分かりません。）

登録出来るように修正しましたのでよろしくお願いします。

2024-02-22 11:06 UTC, hirosi1900day reviewed
@toshinori-m 
コメントしました！

2024-02-22 11:06 UTC, hirosi1900day commented on backend/app/controllers/teams_controller.rb
> +    team_params = create_params
create_paramsメソッドの結果をteam_paramsに入れて利用するのはcreate_paramsをメソッドにする意味がなくなるので、それであればcreate_paramsのメソッド名をtarget_paramsなどにすれば一時変数が減らせると思いますがいかがでしょうか？

2024-02-22 11:06 UTC, hirosi1900day commented on backend/app/controllers/teams_controller.rb
> +    team.target_age_ids = team_params[:target_age_ids]
```
team = current_user.teams.new(team_params)
```

上記だけではうまくいかなかったですかね？？

2024-02-23 01:35 UTC, toshinori-m commented on backend/app/controllers/teams_controller.rb
> +    team.target_age_ids = team_params[:target_age_ids]
```
team = current_user.teams.new(team_params)
```
上のコードで上手くいきました。
申し訳ありません。

上のコードの修正が理解出来たので、recruitments_controller.rbのcreateアクションに似た箇所が有ったので、そちらも修正しました。

よろしくお願いします。

2024-02-23 10:37 UTC, hirosi1900day approved these changes
LGTM！

2024-02-23 10:49 UTC, hirosi1900day requested changes

2024-02-23 10:49 UTC, hirosi1900day commented on frontend/src/views/TeamProfile/TeamProfileEditPage.vue
> +      const nameLength = this.team.name?.length ?? 0
typescritpではなく、javascriptなので?は不要かと
```suggestion
      const nameLength = this.team.name.length ?? 0
```

2024-02-24 02:59 UTC, hirosi1900day approved these changes
LGTM!

2024-02-24 03:16 UTC, merged