Firebaseへ移行によるSportsType関係修正
toshinori-m/stay_connect pull request #63
Opened 2023-12-13 04:23 UTC by toshinori-m

Firebaseへ移行によるSportsType関係修正を追加しました。

2023-12-13 12:11 UTC, hirosi1900day requested changes
こちらもaxiosのインスタンスを使ってaxiosリクエストするようにした方が良さそうですね！

2023-12-13 12:11 UTC, hirosi1900day commented on frontend/src/views/MakingIntroductions/SportsDisciplineEditPage.vue
> +      error: null
[ask]
errorを配列からnullに変えたのは理由がありますか？？
配列でないとエラーが全てのメソッドでリセットされて、2つ以上エラーが発生した場合にうまく動かなそうな気がしたのでご質問です！

2023-12-14 01:56 UTC, toshinori-m commented on frontend/src/views/MakingIntroductions/SportsDisciplineEditPage.vue
> +      error: null
get、patch、deleteアクションの全てthis.errors.push('')のように文字を単独でpushするような形になっていました。
そして、アクションの最初にthis.errors = []があるので、エラーを消すようにしています。
ということは、2つ以上エラーが同時に発生することが無いので修正したのですが、この考え方が誤りのようなら元へ戻す修正をします。

2023-12-14 06:03 UTC, hirosi1900day approved these changes
OK!!

2023-12-14 07:52 UTC, merged